obj-$(CONFIG_IMX8MP_DSI_CROSSLINK_OLED) += imx8mp-dsi-crosslink-oled.o
obj-$(CONFIG_IMX8MP_DSI_CROSSLINK_OLED) += imx8mp-i2c-oled-800x600.o
obj-$(CONFIG_IMX8MP_DSI_CROSSLINK_OLED) += imx8mp-i2c-oled-1280x1024.o
